export const  PASSENGER_REQUEST="PASSENGER_REQUEST"
export const  PASSENGER_FAILURE="PASSENGER_FAILURE"
export const  PASSENGER_SUCCESS="PASSENGER_SUCCESS"
export const  PASSENGER_LOGINSUCCESS="PASSENGER_LOGINSUCCESS"